### ISSUE TITLE
demo example does not work

### ISSUE THREAD

**Issue by Finfalter** [bytecodealliance/wasmtime-py#114]
So I have these three files:

1. demo.wat
2. demo.wit
3. demo.py

Then, `wasm-tools component new demo.wat --wit demo.wit -o demo.wasm` creates **demo.wasm** as expected but `python -m wasmtime.bindgen demo.wasm --out-dir demo` generates the following error:

```bash
$ python3 -m wasmtime.bindgen demo.wasm --out-dir demo
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/<path>/.local/lib/python3.10/site-packages/wasmtime/bindgen/__main__.py", line 40, in <module>
    main()
  File "/<path>/.local/lib/python3.10/site-packages/wasmtime/bindgen/__main__.py", line 30, in main
    files = generate(name, contents)
  File "/<path>/.local/lib/python3.10/site-packages/wasmtime/bindgen/__init__.py", line 40, in generate
    raise RuntimeError(result.value)
RuntimeError: failed to extract interface information from component

Caused by:
    invalid leading byte (0x1) for component external kind (at offset 0x25)

```
Could you please give me a hint how to make the initial example work?

**Comment by alexcrichton** [comment]
One thing I should also point out is that things are in flux right now as the binary format is changing and all the tooling needs to be kept in sync. It's expected the binary format will settle before stabilization but in the meantime if you'd like to work with things you'll need to use the "bleeding edge" of tools generally to ensure that everything is in sync.
