### ISSUE TITLE
RuntimeError: failed to extract interface information from component

### ISSUE THREAD

**Issue by danbev** [bytecodealliance/wasmtime-py#151]
I ran into the following error when trying to extract types into a separate interface:
```console
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/danielbevenius/.local/lib/python3.11/site-packages/wasmtime/bindgen/__main__.py", line 40, in <module>
    main()
  File "/home/danielbevenius/.local/lib/python3.11/site-packages/wasmtime/bindgen/__main__.py", line 30, in main
    files = generate(name, contents)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/danielbevenius/.local/lib/python3.11/site-packages/wasmtime/bindgen/__init__.py", line 40, in generate
    raise RuntimeError(result.value)
RuntimeError: failed to extract interface information from component

Caused by:
    0: failed to decode WIT from export `wit`
    1: unexpected unnamed type of kind 'record'
```
I've created a [reproducer](https://github.com/danbev/wasmtime-py/blob/runtime-error/demo/README.md) which contains some more details about this issue and might be helpful. I'll try to figure out what the error is but wanted to create this issue to get some more visibility in case someone has already ran into this before.

**Comment by alexcrichton** [comment]
Thanks for the report! I think this should be fixed by https://github.com/bytecodealliance/wasmtime-py/pull/154

**Comment by danbev** [comment]
@alexcrichton Thanks for the quick fix!
