### ISSUE TITLE
Panic with wasmtime 10, WIT and component model 0xd

### ISSUE THREAD

**Issue by zifeo** [bytecodealliance/wasmtime-py#161]
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/USER/Documents//metatype/.venv/lib/python3.11/site-packages/wasmtime/bindgen/__main__.py", line 40, in <module>
    main()
  File "/Users/USER/Documents/metatype/.venv/lib/python3.11/site-packages/wasmtime/bindgen/__main__.py", line 30, in main
    files = generate(name, contents)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/USER/Documents/metatype/.venv/lib/python3.11/site-packages/wasmtime/bindgen/__init__.py", line 117, in generate
    result = root.generate(store, name, component)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/USER/Documents/metatype/.venv/lib/python3.11/site-packages/wasmtime/bindgen/generated/__init__.py", line 238, in generate
    ret = self.lift_callee0(caller, ptr, len0, ptr1, len2)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/USER/Documents/metatype/.venv/lib/python3.11/site-packages/wasmtime/_func.py", line 91, in __call__
    with enter_wasm(store) as trap:
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/Users/USER/Documents/metatype/.venv/lib/python3.11/site-packages/wasmtime/_func.py", line 264, in enter_wasm
    raise trap_obj
wasmtime._trap.Trap: error while executing at wasm backtrace:
    0: 0x19eb36 - <unknown>!__rust_start_panic
    1: 0x19e89f - <unknown>!rust_panic
    2: 0x19e872 - <unknown>!std::panicking::rust_panic_with_hook::h51603b60b23a0fb8
    3: 0x19d991 - <unknown>!std::panicking::begin_panic_handler::{{closure}}::h376f292379b1d694
    4: 0x19d8bb - <unknown>!std::sys_common::backtrace::__rust_end_short_backtrace::h0b174033ce8c7f4e
    5: 0x19df4f - <unknown>!rust_begin_unwind
    6: 0x1a3d39 - <unknown>!core::panicking::panic_fmt::h0724b0a601bd3679
    7: 0x1a9f6a - <unknown>!core::option::expect_failed::h001f1263852c0fc9
    8: 0x37004 - <unknown>!<indexmap::map::IndexMap<K,V,S> as core::ops::index::Index<&Q>>::index::hba1c32b5e24b72fd
    9: 0x7466 - <unknown>!bindgen::bindgen::WasmtimePy::generate::h1dfdba5148560cf7
   10: 0x22489 - <unknown>!<bindgen::bindings::PythonBindings as bindgen::bindings::Bindgen>::generate::h5738c7fa877c054b
   11: 0x22678 - <unknown>!generate

Caused by:
    wasm trap: wasm `unreachable` instruction executed
thread '<unnamed>' panicked at 'IndexMap: key not found', bindgen/src/bindgen.rs:768:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

[Repro](https://github.com/metatypedev/metatype/tree/deps) & [WIT files](https://github.com/metatypedev/metatype/tree/deps/typegraph/core/wit) with:

```
cargo build -p typegraph_core --target wasm32-unknown-unknown -F wasm
wasm-tools component new target/wasm32-unknown-unknown/debug/typegraph_core.wasm -o target/debug/typegraph_core.wasm
poetry run python -m wasmtime.bindgen target/debug/typegraph_core.wasm --out-dir typegraph/python_next/typegraph_next/gen
```

How should this be debugged further? Note that this did not happen with component model 0xc and wasmtime 9.0.0 (see main branch).

**Comment by alexcrichton** [comment]
Thanks for the report! Just a regular old bug and this should be fixed by https://github.com/bytecodealliance/wasmtime-py/pull/162

**Comment by zifeo** [comment]
@alexcrichton Awesome thanks, do you plan a bug fix release or shall I build from main?

**Comment by alexcrichton** [comment]
If building from main works for you there will be a 11.0.0 release in a few days so I can publish this with that then

**Comment by zifeo** [comment]
@alexcrichton the build with rust makes it hard to get on all our environment (e.g. ci), is there a way to get a bug fix release for that or that's too much work?

**Comment by alexcrichton** [comment]
Ok sure I can do a point release
