### ISSUE TITLE
Error when using wasm file with arrays

### ISSUE THREAD

**Issue by MatteoPossamai** [bytecodealliance/wasmtime-py#167]
Hi. I am new to WebAssembly. I found a way to traduce Typescript file into WASM file, and then I would like to consume the function in python. Here is the code that gets compiled from typescript:

```
export function add(a: i32, b: i32): i32 {
  return a + b;
}

export function prova(x: i32, y: i32): i32{
  return x * y;
}

export function rr(x: Int32Array): i32 {
  return 2;
}
```

And here is the Python code I use to consume the wasm file generated by the compilation:
```
import wasmtime.loader
import build.release as release

print(release.add(5,2))
print(release.prova(5,2))
```
If I compile the typescript file with only the first two functions, everything works properly. If I compile it with the last one too, I get the following error: 
```
Traceback (most recent call last):
  File "/Users/mposs/Desktop/wasm/wasm_py.py", line 2, in <module>
    import build.release as release
  File "/Users/mposs/Library/Python/3.9/lib/python/site-packages/wasmtime/loader.py", line 72, in exec_module
    imported_module = importlib.import_module(module_name)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'env'
```
If I try to install the module, and re-run, I get this error: 
```
Traceback (most recent call last):
  File "/Users/mposs/Desktop/wasm/wasm_py.py", line 2, in <module>
    import build.release as release
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/Users/mposs/Desktop/wasm/venv/lib/python3.9/site-packages/wasmtime/loader.py", line 72, in exec_module
    imported_module = importlib.import_module(module_name)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/mposs/Desktop/wasm/venv/lib/python3.9/site-packages/env.py", line 51
    print k
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(k)?
```

Some ideas?

**Comment by alexcrichton** [comment]
Thanks for the report, can you share the wasm module in question? My guess is that you're using assemblyscript which is injecting imports that you need to satisfy which aren't being satisfied. The `env` module is the "default" module imported by `wasm-ld` and the `env` module in Python is different and unrelated.

**Comment by MatteoPossamai** [comment]
yes, I am using it. Do you know some way that I can avoid this problem? Or should I just find another compiler?

**Comment by alexcrichton** [comment]
I don't personally know of a way to run assemblyscript off-the-web, so you'll want to consult their documentation about doing this. Otherwise you'll want to consult someone more knowledgeable about assemblyscript.
