### ISSUE TITLE
bug: sched_yield is not defined

### ISSUE THREAD

**Issue by HarikrishnanBalagopal** [bytecodealliance/wasmtime-py#223]
```
$ python3 main.py 
Traceback (most recent call last):
  File "............../test-py-wasmtime/main.py", line 63, in <module>
    main()
  File "............../test-py-wasmtime/main.py", line 53, in main
    instance = linker.instantiate(store=store, module=module)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/haribala/Documents/code/remote/github.com/HarikrishnanBalagopal/test-py-wasmtime/.venv/lib/python3.11/site-packages/wasmtime/_linker.py", line 171, in instantiate
    raise WasmtimeError._from_ptr(error)
wasmtime._error.WasmtimeError: unknown import: `wasi_snapshot_preview1::sched_yield` has not been defined
```

**Comment by alexcrichton** [comment]
Thanks for the report! As I think you've found this needs a `linker.define_wasi()` call. Agreed the docs/examples could be better!
