### ISSUE TITLE
problem loading a component that uses wasi?

### ISSUE THREAD

**Issue by TobyEalden** [bytecodealliance/wasmtime-py#246]
I'm trying to get a working example of using a component with wasi from python.

I have a basic component created using [cargo component](https://github.com/bytecodealliance/cargo-component):

```sh
cargo component new --lib mycomponent
```

I then build the component:

```sh
cargo component build
```

this builds to the default wasm32-wasip1 target, and I copy the `.wasm` file to the root of my python project.

The python code is:

```py
import traceback
from wasmtime import Store, loader

from volt_ws_protocol_component import Root

def main():
    try:
        store = Store()
        component = Root(store)
        hello_response = component.hello_world(store)
        print(hello_response)
    except Exception as e:
        print(f"Failed to call hello: {e}")
        traceback.print_exc()
        
if __name__ == "__main__":
    main()
```

When I run this I get the following error:

```sh
❯ python main.py
thread '<unnamed>' panicked at src/bindgen.rs:2911:29:
not implemented: imported resources not yet supported
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/Users/tobyealden/code/tdxvolt/tdxvolt-rs/python_harness/main.py", line 4, in <module>
    from mycomponent import Root
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "/Users/tobyealden/code/tdxvolt/tdxvolt-rs/python_harness/volt_env/lib/python3.9/site-packages/wasmtime/loader.py", line 153, in find_spec
    _component_bindings[origin] = self.load_component(origin, binary=is_binary)
  File "/Users/tobyealden/code/tdxvolt/tdxvolt-rs/python_harness/volt_env/lib/python3.9/site-packages/wasmtime/loader.py", line 131, in load_component
    return bindgen.generate("root", component)
  File "/Users/tobyealden/code/tdxvolt/tdxvolt-rs/python_harness/volt_env/lib/python3.9/site-packages/wasmtime/bindgen/__init__.py", line 151, in generate
    result = root.generate(store, name, component)
  File "/Users/tobyealden/code/tdxvolt/tdxvolt-rs/python_harness/volt_env/lib/python3.9/site-packages/wasmtime/bindgen/generated/__init__.py", line 301, in generate
    ret = self.lift_callee0(caller, ptr, len0, ptr1, len2)
  File "/Users/tobyealden/code/tdxvolt/tdxvolt-rs/python_harness/volt_env/lib/python3.9/site-packages/wasmtime/_func.py", line 103, in __call__
    raise WasmtimeError._from_ptr(error)
  File "/Users/tobyealden/.pyenv/versions/3.9.19/lib/python3.9/contextlib.py", line 126, in __exit__
    next(self.gen)
  File "/Users/tobyealden/code/tdxvolt/tdxvolt-rs/python_harness/volt_env/lib/python3.9/site-packages/wasmtime/_func.py", line 265, in enter_wasm
    raise trap_obj
wasmtime._trap.Trap: error while executing at wasm backtrace:
    0: 0x21b39e - bindgen.wasm!__rust_start_panic
    1: 0x21b238 - bindgen.wasm!rust_panic
    2: 0x21af5c - bindgen.wasm!std::panicking::rust_panic_with_hook::h5aa58467fd511e58
    3: 0x21a34c - bindgen.wasm!std::panicking::begin_panic_handler::{{closure}}::hddafbb74422ab5b5
    4: 0x21a27c - bindgen.wasm!std::sys_common::backtrace::__rust_end_short_backtrace::hee1cd7216ef8c172
    5: 0x21aa64 - bindgen.wasm!rust_begin_unwind
    6: 0x228092 - bindgen.wasm!core::panicking::panic_fmt::hdff7d27056516045
    7: 0x171c6 - bindgen.wasm!<bindgen::bindgen::FunctionBindgen as wit_bindgen_core::abi::Bindgen>::emit::h371becfed4ef60ed
    8: 0x29fec - bindgen.wasm!wit_bindgen_core::abi::Generator<B>::emit::h73aacf1c591a9bab
    9: 0x2b069 - bindgen.wasm!wit_bindgen_core::abi::Generator<B>::lift::hd694126ede7ccf9e
   10: 0x314cc - bindgen.wasm!wit_bindgen_core::abi::call::h9562672c6a7e0a75
   11: 0xd849 - bindgen.wasm!bindgen::bindgen::Instantiator::bindgen::ha0d69afed3096c45
   12: 0xb6ce - bindgen.wasm!bindgen::bindgen::WasmtimePy::instantiate::hcaee39c0c215ca15
   13: 0x63d5 - bindgen.wasm!bindgen::bindgen::WasmtimePy::generate::h0d55c547f641a6d3
   14: 0x3ebec - bindgen.wasm!<bindgen::bindings::PythonBindings as bindgen::bindings::Guest>::generate::hb5b6ad11d2bacd63
   15: 0x3ed9f - bindgen.wasm!generate

Caused by:
    wasm trap: wasm `unreachable` instruction executed
```

Presumably I have to initialise or link wasi in some way - what is the idiomatic way of doing this when loading components? I couldn't find any documentation or example code.

Note that this works as expected if I use `cargo component build --target wasm32-unknown-unknown`, but I need to be able to use wasi in my component (e.g. to generate a random number).

**Comment by alexcrichton** [comment]
Ah the error you're running into is in the output:

```
not implemented: imported resources not yet supported
```

Resources haven't been implemented in wasmtime-py at this time, which means components using WASI can't be easily loaded at this time. The component support in wasmtime-py is still quite underbaked and not really ready for prime-time.

**Comment by TobyEalden** [comment]
OK, I thought this might be the case - can you give a ballpark ETA of when this might be supported?

Thanks for getting back to me so quickly.

**Comment by alexcrichton** [comment]
No ETA at this time, I don't believe anyone's queued up to work on it
