### ISSUE TITLE
wasmtime.loader: import error when importing a WASM module which has imports

### ISSUE THREAD

**Issue by Keithcat1** [bytecodealliance/wasmtime-py#83]
OS: Windows (10 64-bit), Python 3.9.5, Wasmtime-py 0.35.0
Steps to reproduce:
You need a Rust toolchain (make sure to "rustup target add wasm32-unknown-unknown wasm32-wasi") and the wasm-pack tool
```

C:\py\git>git clone https://github.com/httptoolkit/brotli-wasm
Cloning into 'brotli-wasm'...
remote: Enumerating objects: 84, done.
Receiving objects: 100% (84/84), 25.53 KiB | 2.32 MiB/s, done.(13/84)
Resolving deltas: 100% (37/37), done.)
remote: Counting objects: 100% (84/84), done.
remote: Compressing objects: 100% (53/53), done.
remote: Total 84 (delta 37), reused 63 (delta 21), pack-reused 0

C:\py\git>cd brotli-wasm

C:\py\git\brotli-wasm>wasm-pack build
[INFO]: Checking for the Wasm target...
[INFO]: Compiling to Wasm...
   Compiling proc-macro2 v1.0.36
   Compiling unicode-xid v0.2.2
   Compiling syn v1.0.86
   Compiling wasm-bindgen-shared v0.2.79
   Compiling log v0.4.14
   Compiling cfg-if v1.0.0
   Compiling serde_derive v1.0.136
   Compiling bumpalo v3.9.1
   Compiling serde v1.0.136
   Compiling lazy_static v1.4.0
   Compiling serde_json v1.0.79
   Compiling wasm-bindgen v0.2.79
   Compiling alloc-no-stdlib v2.0.3
   Compiling itoa v1.0.1
   Compiling ryu v1.0.9
   Compiling wee_alloc v0.4.5
   Compiling cfg-if v0.1.10
   Compiling memory_units v0.4.0
   Compiling alloc-stdlib v0.2.1
   Compiling brotli-decompressor v2.3.2
   Compiling quote v1.0.15
   Compiling brotli v3.3.3
   Compiling wasm-bindgen-backend v0.2.79
   Compiling wasm-bindgen-macro-support v0.2.79
   Compiling wasm-bindgen-macro v0.2.79
   Compiling console_error_panic_hook v0.1.7
   Compiling brotli-wasm v1.0.0 (C:\py\git\brotli-wasm)
    Finished release [optimized] target(s) in 55.75s
[INFO]: Installing wasm-bindgen...
[INFO]: Optimizing wasm binaries with `wasm-opt`...
[INFO]: :-) Done in 1m 11s
[INFO]: :-) Your wasm pkg is ready to publish at C:\py\git\brotli-wasm\pkg.

C:\py\git\brotli-wasm>cd pkg

C:\py\git\brotli-wasm\pkg>python
Python 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import wasmtime.loader
>>> import brotli_wasm_bg
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\python\lib\site-packages\wasmtime\loader.py", line 72, in exec_module
    imported_module = importlib.import_module(module_name)
  File "C:\python\lib\importlib\__init__.py", line 122, in import_module
    raise TypeError(msg.format(name))
TypeError: the 'package' argument is required to perform a relative import for './brotli_wasm_bg.js'
>>> exit()

C:\py\git\brotli-wasm\pkg>
```

**Comment by alexcrichton** [comment]
I believe that this is expected in that `wasm-pack` and `wasm-bindgen` are meant for the web and not Python. I think the error here is that you're trying to load the wasm file which references JS files, which isn't compatible with Wasmtime since you'd have to implement all of `wasm-bindgen`'s unstable intrinsics and interfaces in Python.

**Comment by Keithcat1** [comment]
How then can I compile the WASM file to be WASMTIME compatible? Thanks.
